FROM docker.io/debian:bookworm-slim
MAINTAINER CYOSP <cyosp@cyosp.com>

RUN apt update \
    && apt install -y \
      --no-install-recommends \
      nginx \
      php-fpm \
      php-curl \
      supervisor \
      jq \
      bc \
      rrdtool \
      librrds-perl \
      curl \
      ca-certificates \
      zip \
      logrotate \
      cron \
      libgpiod2

# rc-rsl
RUN dist=$(cat /etc/os-release | grep VERSION_CODENAME | cut -d= -f2) \
    && curl -L https://github.com/cyosp/rc-rsl/releases/download/2.1.0/rc-rsl-$dist-$(arch) -o rc-rsl-$dist-$(arch) \
    && curl -L https://github.com/cyosp/rc-rsl/releases/download/2.1.0/rc-rsl-SHA512.txt -o rc-rsl-SHA512.txt \
    && grep rc-rsl-$dist-$(arch) rc-rsl-SHA512.txt | sha512sum -c \
    && rm rc-rsl-SHA512.txt \
    && mv rc-rsl-$dist-$(arch) /usr/bin/rc-rsl \
    && chmod +x /usr/bin/rc-rsl

# cyths-transmitter + cyths-receiver
ADD bin/cyths-* /usr/local/bin
RUN chmod +x /usr/local/bin/cyths*

# rrd2csv
RUN curl https://raw.githubusercontent.com/cyosp/rrd2csv/master/rrd2csv.pl -o /usr/local/bin/rrd2csv.pl \
      && chmod +x /usr/local/bin/rrd2csv.pl

# Nginx
RUN rm -rf /etc/nginx/sites-enabled/default
ADD podman/nginx.conf /etc/nginx/sites-enabled/cyths.conf
RUN sed -i "s/user www-data;/user root;/" /etc/nginx/nginx.conf
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# CYTHS
ADD www /var/www/html/cyths
RUN mkdir -p /etc/cyths /var/lib/cyths/csv /var/lib/cyths/rrd \
  && ln -s /var/www/html/cyths/data/config.json /etc/cyths \
  && ln -s /var/lib/cyths/csv /var/www/html/cyths/data/ \
  && mkdir -p /var/log/cyths \
  && touch /var/log/cyths/cyths-update.log

# PHP-FPM
RUN sed -i -e 's/www-data/root/g' /etc/php/8.2/fpm/pool.d/www.conf
RUN sed -i -e 's/^.\+daemonize.\+$/daemonize = no/' /etc/php/8.2/fpm/php-fpm.conf

# Logrotate
ADD podman/logrotate/cyths* /etc/logrotate.d

# Cron
ADD podman/crontab /etc/cron.d/cyths
RUN chmod 0644 /etc/cron.d/cyths \
      && crontab /etc/cron.d/cyths \
      && mkdir -p /var/log/cyths

EXPOSE 80
VOLUME [ "/etc/cyths", "/var/lib/cyths/csv", "/var/lib/cyths/rrd" ]

# Supervisor
RUN sed -i -e 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf
COPY podman/supervisor.conf /etc/supervisor/conf.d/cyths.conf
CMD /usr/bin/supervisord
